{"uid":"a6e6e39fecc677ce","name":"test_page_title","fullName":"tests.test_example.ExampleTestCase#test_page_title","historyId":"1f00af4742c2562b8d24e8127e7405ec","time":{"start":1755771815059,"stop":1755771815729,"duration":670},"status":"broken","statusMessage":"selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=139.0.7258.127)\nStacktrace:\n#0 0x56356a05001a <unknown>\n#1 0x563569aefa70 <unknown>\n#2 0x563569ae6cf1 <unknown>\n#3 0x563569ad8099 <unknown>\n#4 0x563569ad9de0 <unknown>\n#5 0x563569ad843e <unknown>\n#6 0x563569ad7daa <unknown>\n#7 0x563569ad7a85 <unknown>\n#8 0x563569ad58ee <unknown>\n#9 0x563569ad60ca <unknown>\n#10 0x563569af2f99 <unknown>\n#11 0x563569b8dd65 <unknown>\n#12 0x563569b673e2 <unknown>\n#13 0x563569b8d14f <unknown>\n#14 0x563569b671b3 <unknown>\n#15 0x563569b3359b <unknown>\n#16 0x563569b34971 <unknown>\n#17 0x56356a0151eb <unknown>\n#18 0x56356a018f39 <unknown>\n#19 0x563569ffc2c9 <unknown>\n#20 0x56356a019ae8 <unknown>\n#21 0x563569fe0baf <unknown>\n#22 0x56356a03d0a8 <unknown>\n#23 0x56356a03d286 <unknown>\n#24 0x56356a04eff6 <unknown>\n#25 0x7fa5dcc9caa4 <unknown>\n#26 0x7fa5dcd29c3c <unknown>","statusTrace":"self = <test_example.ExampleTestCase testMethod=test_page_title>\n\n    def test_page_title(self):\n>       self.home.open(OLLAMA_URL)\n\ntests/test_example.py:26: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \npages/home_page.py:21: in open\n    self.driver.get(url)\n/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py:483: in get\n    self.execute(Command.GET, {\"url\": url})\n/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py:458: in execute\n    self.error_handler.check_response(response)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.remote.errorhandler.ErrorHandler object at 0x7fb6f87b4a10>\nresponse = {'status': 500, 'value': '{\"value\":{\"error\":\"unknown error\",\"message\":\"unknown error: net::ERR_CONNECTION_REFUSED\\\\n  ...\\\\n#24 0x56356a04eff6 \\\\u003Cunknown>\\\\n#25 0x7fa5dcc9caa4 \\\\u003Cunknown>\\\\n#26 0x7fa5dcd29c3c \\\\u003Cunknown>\\\\n\"}}'}\n\n    def check_response(self, response: dict[str, Any]) -> None:\n        \"\"\"Checks that a JSON response from the WebDriver does not have an\n        error.\n    \n        :Args:\n         - response - The JSON response from the WebDriver server as a dictionary\n           object.\n    \n        :Raises: If the response contains an error message.\n        \"\"\"\n        status = response.get(\"status\", None)\n        if not status or status == ErrorCode.SUCCESS:\n            return\n        value = None\n        message = response.get(\"message\", \"\")\n        screen: str = response.get(\"screen\", \"\")\n        stacktrace = None\n        if isinstance(status, int):\n            value_json = response.get(\"value\", None)\n            if value_json and isinstance(value_json, str):\n                try:\n                    value = json.loads(value_json)\n                    if isinstance(value, dict):\n                        if len(value) == 1:\n                            value = value[\"value\"]\n                        status = value.get(\"error\", None)\n                        if not status:\n                            status = value.get(\"status\", ErrorCode.UNKNOWN_ERROR)\n                            message = value.get(\"value\") or value.get(\"message\")\n                            if not isinstance(message, str):\n                                value = message\n                                message = message.get(\"message\")\n                        else:\n                            message = value.get(\"message\", None)\n                except ValueError:\n                    pass\n    \n        exception_class: type[WebDriverException]\n        e = ErrorCode()\n        error_codes = [item for item in dir(e) if not item.startswith(\"__\")]\n        for error_code in error_codes:\n            error_info = getattr(ErrorCode, error_code)\n            if isinstance(error_info, list) and status in error_info:\n                exception_class = getattr(ExceptionMapping, error_code, WebDriverException)\n                break\n        else:\n            exception_class = WebDriverException\n    \n        if not value:\n            value = response[\"value\"]\n        if isinstance(value, str):\n            raise exception_class(value)\n        if message == \"\" and \"message\" in value:\n            message = value[\"message\"]\n    \n        screen = None  # type: ignore[assignment]\n        if \"screen\" in value:\n            screen = value[\"screen\"]\n    \n        stacktrace = None\n        st_value = value.get(\"stackTrace\") or value.get(\"stacktrace\")\n        if st_value:\n            if isinstance(st_value, str):\n                stacktrace = st_value.split(\"\\n\")\n            else:\n                stacktrace = []\n                try:\n                    for frame in st_value:\n                        line = frame.get(\"lineNumber\", \"\")\n                        file = frame.get(\"fileName\", \"<anonymous>\")\n                        if line:\n                            file = f\"{file}:{line}\"\n                        meth = frame.get(\"methodName\", \"<anonymous>\")\n                        if \"className\" in frame:\n                            meth = f\"{frame['className']}.{meth}\"\n                        msg = \"    at %s (%s)\"\n                        msg = msg % (meth, file)\n                        stacktrace.append(msg)\n                except TypeError:\n                    pass\n        if exception_class == UnexpectedAlertPresentException:\n            alert_text = None\n            if \"data\" in value:\n                alert_text = value[\"data\"].get(\"text\")\n            elif \"alert\" in value:\n                alert_text = value[\"alert\"].get(\"text\")\n            raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here\n>       raise exception_class(message, screen, stacktrace)\nE       selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\nE         (Session info: chrome=139.0.7258.127)\nE       Stacktrace:\nE       #0 0x56356a05001a <unknown>\nE       #1 0x563569aefa70 <unknown>\nE       #2 0x563569ae6cf1 <unknown>\nE       #3 0x563569ad8099 <unknown>\nE       #4 0x563569ad9de0 <unknown>\nE       #5 0x563569ad843e <unknown>\nE       #6 0x563569ad7daa <unknown>\nE       #7 0x563569ad7a85 <unknown>\nE       #8 0x563569ad58ee <unknown>\nE       #9 0x563569ad60ca <unknown>\nE       #10 0x563569af2f99 <unknown>\nE       #11 0x563569b8dd65 <unknown>\nE       #12 0x563569b673e2 <unknown>\nE       #13 0x563569b8d14f <unknown>\nE       #14 0x563569b671b3 <unknown>\nE       #15 0x563569b3359b <unknown>\nE       #16 0x563569b34971 <unknown>\nE       #17 0x56356a0151eb <unknown>\nE       #18 0x56356a018f39 <unknown>\nE       #19 0x563569ffc2c9 <unknown>\nE       #20 0x56356a019ae8 <unknown>\nE       #21 0x563569fe0baf <unknown>\nE       #22 0x56356a03d0a8 <unknown>\nE       #23 0x56356a03d286 <unknown>\nE       #24 0x56356a04eff6 <unknown>\nE       #25 0x7fa5dcc9caa4 <unknown>\nE       #26 0x7fa5dcd29c3c <unknown>\n\n/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py:232: WebDriverException","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":5,"retriesStatusChange":false,"beforeStages":[{"name":"_unittest_setUpClass_fixture_ExampleTestCase","time":{"start":1755771796646,"stop":1755771796646,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"afterStages":[{"name":"_unittest_setUpClass_fixture_ExampleTestCase::0","time":{"start":1755771816387,"stop":1755771816387,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"labels":[{"name":"parentSuite","value":"tests"},{"name":"suite","value":"test_example"},{"name":"subSuite","value":"ExampleTestCase"},{"name":"host","value":"pkrvmqc4gcfdwos"},{"name":"thread","value":"2495-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.test_example"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[{"uid":"5fdefd3f68aa62bf","status":"broken","statusDetails":"selenium.common.exceptions.WebDriverException: Message: Reached error page: about:neterror?e=connectionFailure&u=http%3A//34.245.153.13%3A3000/&c=UTF-8&d=Firefox%20can%E2%80%99t%20establish%20a%20connection%20to%20the%20server%20at%2034.245.153.13%3A3000.\nStacktrace:\nRemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nWebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:199:5\nUnknownError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:910:5\ncheckReadyState@chrome://remote/content/marionette/navigate.sys.mjs:59:24\nonNavigation@chrome://remote/content/marionette/navigate.sys.mjs:348:39\nemit@resource://gre/modules/EventEmitter.sys.mjs:156:19\nreceiveMessage@chrome://remote/content/marionette/actors/MarionetteEventsParent.sys.mjs:33:25","time":{"start":1755771806543,"stop":1755771808859,"duration":2316}},{"uid":"a4946a9ffb4322ad","status":"broken","statusDetails":"selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=139.0.7258.127)\nStacktrace:\n#0 0x558f19de701a <unknown>\n#1 0x558f19886a70 <unknown>\n#2 0x558f1987dcf1 <unknown>\n#3 0x558f1986f099 <unknown>\n#4 0x558f19870de0 <unknown>\n#5 0x558f1986f43e <unknown>\n#6 0x558f1986edaa <unknown>\n#7 0x558f1986ea85 <unknown>\n#8 0x558f1986c8ee <unknown>\n#9 0x558f1986d0ca <unknown>\n#10 0x558f19889f99 <unknown>\n#11 0x558f19924d65 <unknown>\n#12 0x558f198fe3e2 <unknown>\n#13 0x558f1992414f <unknown>\n#14 0x558f198fe1b3 <unknown>\n#15 0x558f198ca59b <unknown>\n#16 0x558f198cb971 <unknown>\n#17 0x558f19dac1eb <unknown>\n#18 0x558f19daff39 <unknown>\n#19 0x558f19d932c9 <unknown>\n#20 0x558f19db0ae8 <unknown>\n#21 0x558f19d77baf <unknown>\n#22 0x558f19dd40a8 <unknown>\n#23 0x558f19dd4286 <unknown>\n#24 0x558f19de5ff6 <unknown>\n#25 0x7f650609caa4 <unknown>\n#26 0x7f6506129c3c <unknown>","time":{"start":1755771805356,"stop":1755771806178,"duration":822}},{"uid":"d5e1546df4ffef9e","status":"broken","statusDetails":"selenium.common.exceptions.WebDriverException: Message: Reached error page: about:neterror?e=connectionFailure&u=http%3A//34.245.153.13%3A3000/&c=UTF-8&d=Firefox%20can%E2%80%99t%20establish%20a%20connection%20to%20the%20server%20at%2034.245.153.13%3A3000.\nStacktrace:\nRemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nWebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:199:5\nUnknownError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:910:5\ncheckReadyState@chrome://remote/content/marionette/navigate.sys.mjs:59:24\nonNavigation@chrome://remote/content/marionette/navigate.sys.mjs:348:39\nemit@resource://gre/modules/EventEmitter.sys.mjs:156:19\nreceiveMessage@chrome://remote/content/marionette/actors/MarionetteEventsParent.sys.mjs:33:25","time":{"start":1755771804746,"stop":1755771807448,"duration":2702}},{"uid":"bc8fc9fdc9028a8d","status":"broken","statusDetails":"selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=139.0.7258.127)\nStacktrace:\n#0 0x5589c1d5901a <unknown>\n#1 0x5589c17f8a70 <unknown>\n#2 0x5589c17efcf1 <unknown>\n#3 0x5589c17e1099 <unknown>\n#4 0x5589c17e2de0 <unknown>\n#5 0x5589c17e143e <unknown>\n#6 0x5589c17e0daa <unknown>\n#7 0x5589c17e0a85 <unknown>\n#8 0x5589c17de8ee <unknown>\n#9 0x5589c17df0ca <unknown>\n#10 0x5589c17fbf99 <unknown>\n#11 0x5589c1896d65 <unknown>\n#12 0x5589c18703e2 <unknown>\n#13 0x5589c189614f <unknown>\n#14 0x5589c18701b3 <unknown>\n#15 0x5589c183c59b <unknown>\n#16 0x5589c183d971 <unknown>\n#17 0x5589c1d1e1eb <unknown>\n#18 0x5589c1d21f39 <unknown>\n#19 0x5589c1d052c9 <unknown>\n#20 0x5589c1d22ae8 <unknown>\n#21 0x5589c1ce9baf <unknown>\n#22 0x5589c1d460a8 <unknown>\n#23 0x5589c1d46286 <unknown>\n#24 0x5589c1d57ff6 <unknown>\n#25 0x7ff54f49caa4 <unknown>\n#26 0x7ff54f529c3c <unknown>","time":{"start":1755771804531,"stop":1755771805333,"duration":802}},{"uid":"f361a87b4a45e172","status":"broken","statusDetails":"selenium.common.exceptions.WebDriverException: Message: Reached error page: about:neterror?e=connectionFailure&u=http%3A//34.245.153.13%3A3000/&c=UTF-8&d=Firefox%20can%E2%80%99t%20establish%20a%20connection%20to%20the%20server%20at%2034.245.153.13%3A3000.\nStacktrace:\nRemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nWebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:199:5\nUnknownError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:910:5\ncheckReadyState@chrome://remote/content/marionette/navigate.sys.mjs:59:24\nonNavigation@chrome://remote/content/marionette/navigate.sys.mjs:348:39\nemit@resource://gre/modules/EventEmitter.sys.mjs:156:19\nreceiveMessage@chrome://remote/content/marionette/actors/MarionetteEventsParent.sys.mjs:33:25","time":{"start":1755771801648,"stop":1755771803818,"duration":2170}}],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"tags":[]},"source":"a6e6e39fecc677ce.json","parameterValues":[]}